### ISSUE TITLE
Asset layers from different rooms with same name override each other

### ISSUE THREAD

**Issue by ArendPeter** [glebtsereteli/GMRoomLoader#1]
Hello, I'm really enjoying the tool so far!

Wanted to report a issue I hit 

## The problem
The rooms that I'm loading all share the same layer names. When I load multiple rooms with the same asset layer name, then which ever one is loaded last with override the content of the previous rooms. 

## Desired Behaviour
For example, let's say I have 3 rooms and each has a sprite layer called "Assets_0" with a single sprite in it. 

If I loaded all 3 rooms with ``RoomLoader.load``, then I would expect the "Assets_0" layer to have 3 sprites

## Work around
I fixed this by adding the following line at the top of ``__roomloader_create_layer``

```
if(layer_exists(_data.prefixed_name)) return layer_get_id(_data.prefixed_name);
```

This may or may not be an acceptable full fix since it only applies of the layer properties of whichever room is loaded first. Not sure what the best approach would be for a full fix

## Side Note
I also noticed that layer_sprite_yscale is commented out in __DataSprite, I assume this is unintentional?

**Comment by glebtsereteli** [comment]
Hey, thanks for reporting this! I've actually been expecting this one.

Before we move forward with the fix, I'd like to clarify something.
> When I load multiple rooms with the same asset layer name, then which ever one is loaded last with override the content of the previous rooms.

When you say "override the content of the previous rooms.", do you mean you lose the previously loaded sprites? Because that shouldn't be the case. You can see me load multiple rooms that share many layer names in the demo project and all those layers can exist alongside each other just fine.

OR do the previously loaded sprites still exist (which they should), but are on different layers? And you want them to be on the same layer, as you suggested under Desired Behavior?

**Comment by glebtsereteli** [comment]
> I also noticed that layer_sprite_yscale is commented out in __DataSprite, I assume this is unintentional?

As for this, it's actually intentional. There's a bug in the current version of GM that provides the `xscale` value for BOTH `xscale` and `yscale`. This is mentioned under [Known Issues](https://github.com/glebtsereteli/GMRoomLoader/wiki/Known-Issues#%EF%B8%8F-sprite-element-data-provides-wrong-image_yscale-values---image_xscale-is-used-for-both).

It is fixed in 2024.2 Beta and I'll uncomment that line as soon as it makes its way into Monthly later this month.

**Comment by ArendPeter** [comment]
Thanks for the clarification!

I may have misdiagnosed what's happening. Here's my specific workflow that wasn't working:

Our game will have a lot of consumable items that use the same object but with different sprites. Since I didn't want to create separate objects, we instead place all the sprites on a "Items" asset layer. Then a script loops over all those sprites to create objects

Initially the code couldn't find the Items layer, but then I realized that the tool was renaming the items layer to to "__roomloader__Items". After updating the layer name in the script I noticed it would only work for 1 of the imported rooms.

Sounds like only one of the imported rooms will get the "__roomloader__Items" layer name, and then the other Item layers will get named something else?

**Comment by glebtsereteli** [comment]
Ah, I see. We can make that work.

[RoomLoader](https://github.com/glebtsereteli/GMRoomLoader/wiki/RoomLoader()-static-constructor-%E2%80%90-main-interface)'s [.load()](https://github.com/glebtsereteli/GMRoomLoader/wiki/RoomLoader()-static-constructor-%E2%80%90-main-interface#-loadroom-x-y-originroomloader_default_origin-flagsroomloader_default_flags---structroomloaderreturndata-or-undefined) method returns an instance of [RoomLoaderReturnData](https://github.com/glebtsereteli/GMRoomLoader/wiki/RoomLoaderReturnData()-constructor-%E2%80%90-returned-data-handler), which has a [.get_layer()](https://github.com/glebtsereteli/GMRoomLoader/wiki/RoomLoaderReturnData()-constructor-%E2%80%90-returned-data-handler#-get_layername---idlayer-or-undefined) method you can use to retrieve the layer ID using its string name (without GMRoomLoader's prefix):
```js
var _data = RoomLoader.load(rm_your_room, x, y);
var _layer = _data.get_layer("Items");
if (_layer != undefined) {
    var _sprites = layer_get_all_elements(_layer);
    // Loop over the sprites, create instances...
}
```

> [!Warning]
> I also found a typo while testing this and released a [patch](https://github.com/glebtsereteli/GMRoomLoader/releases/tag/v1.4.1), make sure to update to it for this to work properly :)

**Comment by glebtsereteli** [comment]
Alternatively, if your room only has a single Asset layer with those item sprites on it, you can use [RoomLoaderReturnData](https://github.com/glebtsereteli/GMRoomLoader/wiki/RoomLoaderReturnData()-constructor-%E2%80%90-returned-data-handler)'s [.get_sprites()](https://github.com/glebtsereteli/GMRoomLoader/wiki/RoomLoaderReturnData()-constructor-%E2%80%90-returned-data-handler#-get_sprites---arrayidsprite) method to get an array of loaded sprites directly.

**Comment by ArendPeter** [comment]
Thanks for the response, and sorry for the delay!

I updated the library, and used the get_layer() approach that you recommended and it worked great :D

I'll close this issue, but I'll be sure to let you know if I have any more questions
