### ISSUE TITLE
layer_whitelist_reset() makes the whitelist block all layers

### ISSUE THREAD

**Issue by TM-yt** [glebtsereteli/GMRoomLoader#2]
on version 1.5.1 no layers are loading after using `layer_whitelist_reset()`
instead of reverting to default "all layers load", it makes the whitelist empty, in a way, that no layer are on the whitelist, so no layers load unless `layer_whitelist_add()` is used

**Comment by glebtsereteli** [comment]
Whitelisting works as intended, Modlich's issue is coming from elsewhere. Closing this.
