### ISSUE TITLE
[HTML5] GetObjectIndex is not a function

### ISSUE THREAD

**Issue by x8c8r** [glebtsereteli/GMRoomLoader#3]
I don't really know if it's an issue with the library or with my code, but it seems to come from `RoomLoader.load` function

My code is a bit complex, so I won't try to fit it all in, because frankly it doesn't matter, but to sum it up it's something like
```gml
var pos = get_positions()
var p = RoomLoader.load(rooms[currrent_room], pos[0], pos[1]);
```
It works perfectly well on Windows, but it breaks on HTML5 with an error: 
```
Uncaught TypeError: yyInst(...).GetObjectIndex is not a function
    at gml_Script_anon_314_anon_270___RoomLoaderData___RoomLoaderInternalConstructors
    at array_map
    at gml_Script_anon_270___RoomLoaderData___RoomLoaderInternalConstructors 
    at _xx.gml_Script___RoomLoaderData
    at __yy_gml_object_create
    at gml_Script_anon_292____struct___3_RoomLoader_RoomLoaderMain 
    at Object._tl3 
    at gml_Script_anon_1456_RoomLoader_RoomLoaderMain
    at gml_Script_generate_room (this would be the script which im calling from)
```
I did some digging, it appears to come from line 33 of `__RoomLoaderInternalConstructors` - `_data.sprite = object_get_sprite(_data.object_index);`

I have no idea what to do, is there something wrong with HTML5 or am I just doing something wrong?

**Comment by glebtsereteli** [comment]
Hey! HTML5 isn't currently supported. I mentioned it on the itch page, but not here in the repo. I'll make sure to include that.

As for the error itself - I'll be looking into it when I finally get to HTML5 support. That won't be any time soon though, so feel free to look at the [HTML5 source code](https://github.com/YoYoGames/GameMaker-HTML5) and try to figure it out yourself (they accept PRs there, see the [Contributing](https://github.com/YoYoGames/GameMaker-HTML5#contributing) section in the README).

**Comment by glebtsereteli** [comment]
> I have no idea what to do, is there something wrong with HTML5 or am I just doing something wrong?

As for this, I'm pretty sure it's just another HTML5 problem, given everything works on Windows and Mac.

**Comment by x8c8r** [comment]
> Hey! HTML5 isn't currently supported. I mentioned it on the itch page, but not here in the repo. I'll make sure to include that.

Ah okay, thanks! I did miss that.
